[firmware]
ble_advertising_time_ms=10000
sleep_time_us=180000000
red_led_flash_ms=2

[database]
url=sqlite:////home/j/.local/share/openhcult/sensor_readings.db

[logging]
path=/home/j/test_hcult
stdout=true

[ctrl]
host=127.0.0.1
port=8000
