[ble]
service_uuid=12345678-1234-1234-1234-1234567890ab
characteristic_uuid=abcdefab-1234-5678-1234-abcdefabcdef

[firmware]
ble_advertising_time_ms=45000
sleep_time_us=10000000
n_sleeps_per_transmission=6

[database]
path=~/.local/share/openhcult/sensor_readings.db
