[firmware]
ble_advertising_time_ms=5000
sleep_time_us=5000000
n_sleeps_per_transmission=2
sensor_buffer_size=512
red_led_flash_ms=2

[database]
url=sqlite:////home/j/.local/share/openhcult/sensor_readings.db

[logging]
path=/home/j/test_hcult
stdout=true

[ctrl]
host=127.0.0.1
port=8000
