grafana_admin_user: admin
grafana_admin_password: ""
grafana_http_addr: 0.0.0.0
grafana_http_port: 3000
grafana_default_home_dashboard: /etc/grafana/provisioning/dashboards/openhcult-dashboard.json
grafana_postgres_host: 127.0.0.1
grafana_postgres_port: 5432
