apiVersion: 1

datasources:
  - name: OpenHCult Ctrl
    type: marcusolsson-json-datasource
    uid: openhcult-ctrl
    access: proxy
    isDefault: false
    url: ${OPENHCULT_CTRL_URL}
    jsonData:
      httpMethod: GET
