apiVersion: 1

datasources:
  - name: OpenHCult Postgres
    type: postgres
    uid: openhcult-postgres
    access: proxy
    isDefault: true
    url: ${OPENHCULT_POSTGRES_HOST}:${OPENHCULT_POSTGRES_PORT}
    user: hcult
    secureJsonData:
      password: ${OPENHCULT_DATABASE_PASSWORD}
    jsonData:
      database: hcult
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
