[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hcultutils"
version = "0.0.1"
description = "Utilities for openhcult"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [
    { name = "nobody", email = "nobody@nowhere.com" }
]

dependencies = [
    "matplotlib",
    "numpy",
    "hcultinf",
]

[project.scripts]
infer_events = "hcultutils.infer_events:main"
hcultutils = "hcultutils.cli:main"
