[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hcultmon"
version = "0.0.1"
description = "Plant bluetooth monitor backend"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [
    { name = "nobody", email = "nobody@nowhere.com" }
]

dependencies = [
    "bleak",
    "psycopg[binary]",
    "hcultdb",
]

[project.optional-dependencies]

[project.scripts]
hcultmon = "hcultmon.__main__:main"
